apiVersion: v1
kind: Secret
metadata:
  name: the-test-db
type: Opaque
stringData:
  DB_PASSWORD: REPLACE_WITH_LONG_RANDOM_DATABASE_PASSWORD
  MARIADB_ROOT_PASSWORD: REPLACE_WITH_LONG_RANDOM_ROOT_PASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: the-test-admin
type: Opaque
stringData:
  INITIAL_ADMIN_USERNAME: admin
  INITIAL_ADMIN_PASSWORD: REPLACE_WITH_INITIAL_ADMIN_PASSWORD
